name: Обновление данных с Reverb

on:
  workflow_dispatch:  # Запуск только вручную

jobs:
  scrape-reverb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt

      - name: Run Reverb scraper
        id: scraper
        run: |
          cd scraper
          python -c "from reverb_scraper import scrape_reverb; import json; import datetime; guitars = scrape_reverb(); print(f'::set-output name=count::{len(guitars)}'); timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'); with open('../web/data/reverb_time.json', 'w') as f: json.dump({'last_updated': timestamp, 'count': len(guitars)}, f)"

      - name: Update data in repository
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/
          git add web/data/
          git commit -m "Обновление данных с Reverb - найдено ${{ steps.scraper.outputs.count }} гитар" || echo "No changes to commit"
          git push